name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "python"
          use-pylint: true
          use-pycodestyle: true
          use-flake8: true
          use-black: true
          use-mypy: true
          use-isort: true

