name: Code Review
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v3
      - name: Codeball AI Code Review
        uses: sturdy-dev/codeball-action@v2.6.0

